baseurl: '/'
permalink: pretty
title: 'RIPEDA Consulting'

# Site metadata
description: "Calgary's Apple Certified Consultants. Over 13 years managing Apple devices for businesses, education, and enterprises."
url: "https://ripeda.com"
locale: en_CA
timezone: America/Edmonton

# SEO-specific settings
seo:
  type: Organization
  name: RIPEDA Consulting
  links:
    - https://www.linkedin.com/company/ripeda-consulting
    - https://twitter.com/ripedaconsulting

    # Business Information for Local SEO
business:
  name: "RIPEDA Consulting"
  founded: 2011
  street_address: "300 - 1301 8 Street SW"
  city: "Calgary" 
  province: "Alberta"
  postal_code: "T2R 1B7"
  country: "Canada"
  phone: "+1-844-474-7332"
  email: "info@ripeda.com"

  # Social Media
social:
  name: RIPEDA Consulting
  links:
    - https://www.linkedin.com/company/ripeda-consulting
    - https://twitter.com/ripedaconsulting

# Default SEO settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/images/logo/ripeda-og-image.jpg"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "default"
      image: "/images/logo/ripeda-og-image.jpg"
      keywords: "Apple consulting Alberta, Mac support Calgary Edmonton Red Deer, Apple certified consultants Alberta, IT services Lethbridge, Apple device management Alberta"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
      image: "/images/logo/ripeda-og-image.jpg"
  - scope:
      path: "business-resources"
    values:
      layout: "none"
      robots: "noindex, nofollow"

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.png"
  desktop_height: "32px"

home:
  limit_services: 6

# Collections
collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  business_resources:
    output: false

# Files to include
include:
  - "*.html"
  - "business-resources"

# Files and folders to exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - "business-resources/assets/logs/"
  - "*.log"
  - "package*.json"

# Security: Keep certain files
keep_files:
  - "business-resources/assets"

# Default layouts
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: "business-resources"
    values:
      layout: "none"

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass configuration
sass:
  style: compressed

# Site navigation
navigation:
  - title: "Services"
    url: "#services"
  - title: "Device as a Service"
    url: "/daas/"
  - title: "Repairs"
    url: "/repairs/"
  - title: "About" 
    url: "/team/"
  - title: "Contact"
    url: "/contact/"